FROM nginx:alpine

# Nginx config
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Frontend statik dosyalar
COPY frontend/*.html /usr/share/nginx/html/

EXPOSE 80
